Repository EternoSeeker/gameoflife, pull requests merged in 2024-07, with the labels that each got.

#260 Added generation stats
  css/style.css
  index.html
  js/app.js
Labels: enhancement, gssoc, level2

#372 fix music hover and icons toggle
  css/style.css
  index.html
Labels: enhancement, gssoc, level2

#366 added all the keybinds
  README.md
  css/gamerules.css
  gamerules.html
  index.html
  js/app.js
  js/keyboard-shortcut.js
  js/music.js
  js/speed.js
Labels: enhancement, gssoc, level2

#374 Adding a FAQ Page
  .vscode/settings.json
  css/faq.css
  faq.html
  index.html
Labels: enhancement, gssoc, level2

#377 star added in feedback form
  css/feedback.css
  feedback.html
Labels: bug, gssoc, level2

#375 Corrected Mobile view, and tightened the code
  css/style.css
Labels: enhancement, gssoc, level2

#390 Updated README.md
  README.md
Labels: documentation, gssoc, level1

#367 Placed the music button with a check box option in the general settings
  css/style.css
  index.html
  js/app.js
  js/music.js
Labels: bug, gssoc, level1

#408 Added a Logo in Documentation form #203
  Game.md
  images/GameOL.png
Labels: gssoc, level1

#409 Emoji Review Section Added
  css/feedback.css
  feedback.html
Labels: bug, gssoc, level2

#422 Mapped history to keys
  js/keyboard-shortcut.js
Labels: gssoc, level1
