Repository EternoSeeker/gameoflife, pull requests merged in 2024-06, with the labels that each got.

#231 Documentation : Updated README.md
  README.md
Labels: documentation, gssoc, level1

#274 Feedback new design with hover effects
  css/feedback.css
  feedback.html
Labels: gssoc, level2

#280 Added hover effect on texts
  css/style.css
Labels: gssoc, level2

#294 Update README.md
  README.md
Labels: gssoc, level1

#297 Hover effects add on back to home button in gamesrule.css
  css/gamerules.css
Labels: gssoc, level1

#322 Completed and resolved the inconsistent button colour
  css/style.css
Labels: gssoc, level1

#331 FEAT: Added Sweet Alert and themed it
  css/sweet-alert.css
  index.html
  js/app.js
  js/feedback.js
  js/speed.js
Labels: gssoc, level2
