Repository EternoSeeker/gameoflife, pull requests merged in 2024-05, with the labels that each got.

#33 Added aria labels to the buttons
  index.html
Labels: gssoc, Level-1

#37 Added gradient theme button
  index.html
  js/gradient.js
  style.css
Labels: enhancement, gssoc, Level-2

#55 Added the about section in the sidebar menu.
  index.html
  style.css
Labels: gssoc, level1

#61 Fixed conflicts for previous merge
  js/app.js
Labels: gssoc, level2

#106 Updated README.md
  README.md
Labels: documentation, gssoc, level1

#107 Theme selection UI updated
  index.html
Labels: gssoc, level1

#118 Two hamburger icon is showing in mobile view but desktop showing one …
  style.css
Labels: bug, gssoc, level2

#123 Added animation under issue #47 [GGsoC24]
  animation.js
  index.html
  style.css
Labels: enhancement, gssoc, level2

#139 Documents updated for the new Presets
  README.md
  data/game-images/Circle-of-Fire.png
  data/game-images/Pulsar.png
  data/game-images/Quadpole.png
  data/game-images/Spider.png
Labels: documentation, gssoc, level1

#143 Fixed Navbar Responsiveness issue #138
  style.css
Labels: bug, gssoc, level1

#164 Removing Redundant Sidebar Screenshot
  README.md
Labels: gssoc, level1

#163 Uniform hover effect throughout the website
  index.html
Labels: gssoc, level1
